name = "herdmentality"
main = "src/index.ts"
compatibility_date = "2024-04-05"
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "herdmentality-db"
database_id = "2e51338a-dba8-4568-a413-273b1c90db38"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "herdmentality-images"
