name = "herdmentality"
main = "src/index.ts"
compatibility_date = "2024-04-05"
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "herdmentality-db"
database_id = "2c1fce2e-0bf5-414f-b280-2a405b1223d8"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "herdmentality-images"
